[package]
name = "fritiofr_chess"
version = "0.1.2"
edition = "2021"

[lib]
name = "fritiofr_chess"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.48"
